getwd()
setwd("path to your file")
#creating sub folders 
dir.create("raw_data")
dir.create("scripts")
dir.create("clean-data")
dir.create("scripts")
dir.create("plots")          
dir.create("results") 
data <- read.csv(file.choose())
view(data)
str(data)
getwd()
list.files()
#from the class 1b
summary(data)
#changing data as per the nee
data$gender <- as.factor(data$gender)
str(data)
data$diagnosis <- as.factor(data$diagnosi)
str(data)
data$smoker <- as.factor(data$smoker)
str(data)
# creating  binary variable 
data$smoking_binary <- ifelse(data$smoker =="Yes" , 1, 0)
str(data)
names(data)
colnames(data)
head(data)
write.csv(data,"clean-data/data_clean.csv")
